dist: xenial
language: python
python:
  - "3.5"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
     - python3
     - python3-pip
     - taskwarrior
     - notmuch
     - python-notmuch
     - python3-notmuch

env:
  - xPIPENV_IGNORE_VIRTUALENVS=1

install:
  - sudo pip3 install pipenv

script:
  - ./integration_tests.sh
