dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
     - taskwarrior
     - notmuch
     - python-notmuch
     - python3-notmuch

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip3 install pipenv

script:
  - ./integration_tests.sh
