matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: cosmic
    - os: linux
      dist: disco

language: python
python:
  - "3.5"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
     - python3
     - python3-pip
     - taskwarrior
     - notmuch
     - python-notmuch
     - python3-notmuch

env:
  - PIPENV_VERBOSITY=-1

install:
  - sudo pip install pipenv

script:
  - ./integration_tests.sh
