dist: xenial
language: python

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
     - taskwarrior
     - notmuch
     - python-notmuch
     - python3-notmuch

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip3 install pipenv

script:
  - ./integration_tests.sh
