#: To prevent clashes with other exit codes
__EXIT_BASE = 90

EXIT_GENERAL_ERROR = __EXIT_BASE + 0
EXIT_FILE_NOT_FOUND = __EXIT_BASE + 1
EXIT_MESSAGE_NOT_FOUND_IN_NOTMUCH = __EXIT_BASE + 2
EXIT_TASK_NOT_FOUND = __EXIT_BASE + 3
